production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
  options:
    raise_not_found_error: false
staging:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
  options:
    raise_not_found_error: false
development:
  sessions:
    default:
      database: cherche_appart_development
      hosts:
        - localhost:27017
      options:
  options:
    raise_not_found_error: false
test:
  options:
    raise_not_found_error: false
  sessions:
    default:
      database: cherche_appart_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
